export type NavigationTab = 
  | 'home'
  | 'dashboard'
  | 'transcript'
  | 'enhancer'
  | 'converter'
  | 'subtitles'
  | 'screenshots'
  | 'audio'
  | 'downloads'
  | 'pricing'
  | 'blog'
  | 'help'
  | 'admin';

export type TabType = NavigationTab;

export type PlatformId = 'youtube' | 'facebook' | 'instagram' | 'tiktok' | 'vimeo' | 'reddit' | 'x' | 'linkedin' | 'generic';

export interface ServiceSupport {
  id: PlatformId;
  name: string;
  iconName: string;
  logoColor: string;
  badge: string;
  supportedFormats: string[];
  maxQuality: string;
  transcriptSupported: boolean;
  conversionSupported: boolean;
  legalNote: string;
  status: 'Operational' | 'Limited ToS' | 'Transcript Only';
}

export interface VideoResolutionFormat {
  id: string;
  label: string;
  resolution: string;
  container: 'mp4' | 'webm' | 'mkv' | 'mov' | 'mp3' | 'wav' | 'aac' | 'm4a';
  bitrate: string;
  fileSizeEstimate: string;
  fps: number;
  isAudioOnly?: boolean;
  hasAudio: boolean;
}

export interface MediaAnalysisResult {
  url: string;
  title: string;
  platform: PlatformId;
  author: string;
  duration: string;
  durationSeconds: number;
  thumbnailUrl: string;
  views: string;
  uploadDate: string;
  isDownloadAllowed: boolean;
  complianceNotice: string;
  copyrightStatus: 'Public Domain / Authorized' | 'Creative Commons' | 'Standard License (Transcript/AI Only)' | 'Restricted Content';
  availableFormats: VideoResolutionFormat[];
  availableSubtitles: { code: string; name: string; autoGenerated: boolean }[];
  description: string;
}

export interface TranscriptSegment {
  id: string;
  start: string;
  end: string;
  timestampSeconds: number;
  speaker: string;
  text: string;
}

export interface AITranscriptSummary {
  overview: string;
  bulletPoints: string[];
  actionItems: string[];
  keyMoments: { time: string; label: string; description: string }[];
  socialCaptions: { platform: string; text: string; hashtags: string[] }[];
  suggestedBlogTitle: string;
  keywords: string[];
}

export interface DownloadQueueItem {
  id: string;
  title: string;
  platform: PlatformId;
  format: string;
  quality: string;
  fileSize: string;
  progress: number;
  speed: string;
  eta: string;
  status: 'downloading' | 'paused' | 'completed' | 'failed' | 'queued';
  dateAdded: string;
  downloadUrl?: string;
}

export interface ConversionJob {
  id: string;
  filename: string;
  fromFormat: string;
  toFormat: string;
  status: 'processing' | 'completed' | 'queued';
  progress: number;
  outputSize: string;
  outputUrl?: string;
}

export interface AIEnhancementsConfig {
  upscale4K: boolean;
  denoise: boolean;
  sharpen: boolean;
  colorBoost: boolean;
  hdrEnhance: boolean;
  backgroundNoiseRemoval: boolean;
  vocalBooster: boolean;
  speechEnhance: boolean;
  fpsBoost60: boolean;
}

export interface PendingPayment {
  id: string;
  gateway: string;
  amount: number;
  planOrPack: string;
  senderEmail: string;
  senderName: string;
  date: string;
  status: 'Pending Verification' | 'Verified' | 'Rejected';
  transactionNote?: string;
  receiptId: string;
  verifiedAt?: string;
  otpAuthorized?: boolean;
  otpCode?: string;
}

export interface UserProfile {
  id?: string;
  name: string;
  email: string;
  avatar?: string;
  avatarUrl?: string;
  plan: 'Free' | 'Pro' | 'Business';
  aiCreditsRemaining: number;
  totalCredits: number;
  storageUsedGB: number;
  maxStorageGB: number;
  apiKey: string;
  isDarkMode: boolean;
  pendingPayments?: PendingPayment[];
}

export interface BlogPost {
  id: string;
  title: string;
  category: 'Video Tips' | 'AI Tools' | 'Creator Guides' | 'Transcripts' | 'Accessibility';
  readTime: string;
  date: string;
  author: string;
  summary: string;
  imageUrl: string;
}

export interface HelpArticle {
  id: string;
  question: string;
  category: string;
  answer: string;
}
